apiVersion: apps/v1
kind: Deployment
metadata:
    name: aspnetcore30-deployment
spec:
    selector:
        matchLabels:
            app: aspnetcore30-app
            type: aspnetcore30-type
    replicas: 3
    template:
        metadata:
            name: aspnetcore30-pod
            labels:
                app: aspnetcore30-app
                type: aspnetcore30-type
        spec:
            containers:
              - name: aspnetcore30-container
                image: suwatch01/aspnetcore30:latest
---
apiVersion: v1
kind: Service
metadata:
    name: aspnetcore30-nodeport
spec:
    type: NodePort
    ports:
      - port: 80
        targetPort: 80
        nodePort: 30080
    selector:
        app: aspnetcore30-app
        type: aspnetcore30-type