apiVersion: v1
kind: Service
metadata:
    name: aspnetcore30-nodeport
spec:
    type: NodePort
    ports:
      - port: 80
        targetPort: 80
        nodePort: 30080
    selector:
        app: aspnetcore30-app
        type: aspnetcore30-type

